# Generated by Django 5.1 on 2025-08-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeSetter', '0002_user_address_user_work_address_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quest_completed',
            field=models.BooleanField(default=False, help_text='Whether the current quest is completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='quest_description',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quest_file_name',
            field=models.CharField(blank=True, help_text='Name of the uploaded file', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quest_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the currently active quest', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
