# Generated by Django 5.1 on 2025-08-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeSetter', '0003_user_quest_completed_user_quest_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='quest_description',
        ),
    ]
