# Generated by Django 5.1 on 2025-08-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeSetter', '0004_remove_user_quest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quest_id',
            field=models.CharField(blank=True, help_text='ID of the currently active quest', max_length=500, null=True, unique=True),
        ),
    ]
