# Generated by Django 5.1 on 2025-08-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeSetter', '0006_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
