# Generated by Django 5.1 on 2025-08-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeSetter', '0007_alter_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quest_id',
            field=models.IntegerField(blank=True, default=0, help_text='ID of the currently active quest', null=True, unique=True),
        ),
    ]
